### ISSUE TITLE
Status bar not shown

### ISSUE THREAD

**Issue by chjq68** [MSDN-WhiteKnight/WinformsExcel#2]
WinFormsExcelDemo.exe do not show status bar even I checked it.
Env: Windows 7, Office 2010

![statusbar](https://user-images.githubusercontent.com/11057154/90085318-47320400-dd4a-11ea-8bc3-8e761fc6449b.png)

**Comment by MSDN-WhiteKnight** [comment]
It looks like in Excel 2010 and newer the status bar is a part of window frame and can't be shown when window frame is disabled. This behaviour can't be changed, but i can add option to not disable window frame as a workaround.

**Comment by MSDN-WhiteKnight** [comment]
- Added new DisplayWindowTitle property
- Noted in [documentation](http://smallsoft2.blogspot.com/2016/11/winforms-excel-library.html) that DisplayStatusBar has no effect unless DisplayWindowTitle is set to true
- Removed status bar checkbox from demo app. The use of status bar option now is not recommended, because it does not work consistently across Excel versions

Changes published in [v1.3](https://github.com/MSDN-WhiteKnight/WinformsExcel/releases/tag/v1.3)
